//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace csharp_17.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderItem
    {
        public int Id { get; set; }
        public Nullable<int> OrderId { get; set; }
        public Nullable<int> StockId { get; set; }
        public Nullable<decimal> Count { get; set; }
        public Nullable<decimal> SellPrice { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Stock Stock { get; set; }
    }
}
